### PR TITLE
fix(index): crash when used with dynamic `import()`

### LINKED ISSUE #722: [4.0.0-alpha.0] Cannot read property 'requestShortener' of undefined
Using 4.0.0-alpha.0, Webpack 4.0.0-beta.1, Node 9.3.0 on macOS 10.12.6:

Thanks for the hard work on this! Thought I'd try out the new Alpha.0 with my build, looks like I may have found a bug. I'm getting the following error that clearly shows extract-text-webpack-plugin in the stack trace:

```
Fatal error: Cannot read property 'requestShortener' of undefined
TypeError: Cannot read property 'requestShortener' of undefined
    at ConcatenatedModule.source (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/optimize/ConcatenatedModule.js:370:44)
    at Function.renderExtractedChunk (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:115:38)
    at ExtractTextPlugin.extractedChunks.forEach.extractedChunk (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:298:46)
    at Array.forEach (<anonymous>)
    at compilation.hooks.additionalAssets.tapAsync.assetCb (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:286:25)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/Compilation.js:846:32)
    at _err0 (eval at create (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _async2.default.forEach.err (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:281:11)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1050:13)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:958:16
    at _async2.default.forEach.err (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:259:13)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1050:13)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:958:16
    at _async2.default.forEach (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:253:20)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1055:9)
    at eachOf (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3158:5)
    at _async2.default.forEach (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:214:27)
    at /home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1055:9)
    at eachOf (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:3158:5)
    at compilation.hooks.optimizeTree.tapAsync (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/extract-text-webpack-plugin/dist/index.js:208:25)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/Compilation.js:789:27)
    at hooks.make.callAsync.err (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/Compiler.js:446:17)
    at _done (eval at create (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at _err332 (eval at create (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:4004:22)
    at _addModuleChain (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/Compilation.js:672:11)
    at processModuleDependencies.err (/home/app-user/agent/work/841aaf28d3ac9e7f/node_modules/webpack/lib/Compilation.js:614:8)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Task 'webpack:production' took 38925ms
```

Not sure what the best way is to create a minimal project showing issue. Happy to follow-up with more info... Thanks!

### LINKED ISSUE #727: [4.0.0-alpha.0] Cannot read property 'moduleExports' of undefined
I get `TypeError: Cannot read property 'moduleExports' of undefined` after upgrading to webpack 4 and the new alpha of the extract-text plugin:

```
"extract-text-webpack-plugin": "4.0.0-alpha.0",
"webpack": "4.0.0"
```

The stack trace points to `.chunkModule.source()` being called without parameter [here](https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/v4.0.0-alpha.0/src/index.js#L94), which leads to the `runtime` variable being undefined [here](https://github.com/webpack/webpack/blob/master/lib/DelegatedModule.js#L66)

This looks like the same line is causing this as in #722.

**EDIT:** I can confirm that the issue is related to dynamic module loading: If I remove all dynamic import statements, the error goes away (see https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/722#issuecomment-368696250)

Here's the full stack trace:
```
/Users/tz-mac/Repos/pex-client/node_modules/webpack/lib/DelegatedModule.js:66
                        str = `module.exports = (${runtime.moduleExports({
                                                          ^

TypeError: Cannot read property 'moduleExports' of undefined
    at DelegatedModule.source (/Users/tz-mac/Repos/pex-client/node_modules/webpack/lib/DelegatedModule.js:66:38)
    at Function.renderExtractedChunk (/Users/tz-mac/Repos/pex-client/node_modules/extract-text-webpack-plugin/dist/index.js:115:38)
    at ExtractTextPlugin.extractedChunks.forEach.extractedChunk (/Users/tz-mac/Repos/pex-client/node_modules/extract-text-webpack-plugin/dist/index.js:298:46)
    at Array.forEach (<anonymous>)
    at compilation.hooks.additionalAssets.tapAsync.assetCb (/Users/tz-mac/Repos/pex-client/node_modules/extract-text-webpack-plugin/dist/index.js:286:25)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/tz-mac/Repos/pex-client/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/tz-mac/Repos/pex-client/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/Users/tz-mac/Repos/pex-client/node_modules/webpack/lib/Compilation.js:939:32)
    at _err0 (eval at create (/Users/tz-mac/Repos/pex-client/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _async2.default.forEach.err (/Users/tz-mac/Repos/pex-client/node_modules/extract-text-webpack-plugin/dist/index.js:281:11)
    at /Users/tz-mac/Repos/pex-client/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/tz-mac/Repos/pex-client/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
    at /Users/tz-mac/Repos/pex-client/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:906:16
    at _async2.default.forEach.err (/Users/tz-mac/Repos/pex-client/node_modules/extract-text-webpack-plugin/dist/index.js:259:13)
    at /Users/tz-mac/Repos/pex-client/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/tz-mac/Repos/pex-client/node_modules/extract-text-webpack-plugin/node_modules/async/dist/async.js:998:13)
```

### PR DESCRIPTION
**Pull request by Kovensky**
### `Issues`

- Fixes #722 
- Fixes #727

as well as works around an issue where javascript source code of concat modules is being included in extracted css.

### `Notable Changes`

This also works around an issue where `meta.content` can have more than one entry, which I could not figure out how to reproduce for the unit tests, but which was happening in a codebase I am trying to migrate to webpack@4. I don't know if the result is 100% correct, but it compiles, is no longer missing huge amounts of CSS that was definitely supposed to be there, and on quick inspection doesn't seem to have visual artifacts on my page.

This also fixes the commitlint config because it didn't want to let me commit otherwise 🤷‍♀️

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -218,7 +233,9 @@ class ExtractTextPlugin {
               // chunk.sortModules();
 
               async.forEach(
-                Array.from(chunk.modulesIterable),
+                Array.from(chunk.modulesIterable).sort(
+                  (a, b) => a.index - b.index
```
Comment (Kovensky) [inline src/index.js]: This fixes the `chunk-modules-css-wrong-order` test

**Comment by Kovensky** [comment]
I have no idea what is broken in CI but it's not our code 🤔

File: src/index.js (hunk 1 above)
Comment (Kovensky) [reply src/index.js]: Should this use `.index2` instead?

**Comment by evilebottnawi** [comment]
@Kovensky very strange, seems problem in `worker-farm` in uglify plugin :confused:

**Comment by Kovensky** [comment]
I suspect a conflict because of `jsdom`, which `jest` loads by default. `jsdom` might be injecting its own `setTimeout` which doesn't return the same value than node's `setTimeout`. (Browser `setTimeout` returns `number`; node `setTimeout` returns an object)

**Comment by probablyup** [comment]
@Kovensky you should be able to use this comment to disable JSDOM for a test file:

```
/**
 * @jest-environment node
 */
```

File: src/index.js (hunk 1 above)
Comment (michael-ciniawsky) [reply src/index.js]: > `index2` is the ESM evaluation order. `index` is the CJS evaluation order `@sokra` 

`css-loader@latest` returns a CJS module, so `index` should be fine for now. Please add a comment to check/switch to `index2` in case this plugin will see ESM input in the future 😛

File: src/index.js [hunk 2]
```diff
@@ -87,11 +87,20 @@ class ExtractTextPlugin {
     }
   }
 
-  static renderExtractedChunk(chunk) {
+  static renderExtractedChunk(compilation, chunk) {
     const source = new ConcatSource();
 
     for (const chunkModule of chunk.modulesIterable) {
-      let moduleSource = chunkModule.source();
+      let moduleSource = chunkModule.source(
```
Comment (michael-ciniawsky) [inline src/index.js]: https://github.com/webpack/webpack/pull/6597

File: commitlint.config.js [hunk 3]
```diff
@@ -12,7 +12,7 @@ const Configuration = {
     'subject-full-stop': [2, 'never', '.'],
     'type-case': [2, 'always', 'lower-case'],
     'type-empty': [2, 'never'],
-    'type-enum': [
+    'type-enum': [2, 'always', [
```
Comment (michael-ciniawsky) [inline commitlint.config.js]: Revert please, if it is a bug then it needs to be fixed in `webpack-defaults` instead. Not sure actually, seeing this commit messages :D :P https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/728/commits. `git commit -m '...' --no-verify`

File: src/index.js (hunk 2 above)
Comment (Kovensky) [reply src/index.js]: That workaround breaks for other types of Module; it's best to just treat these 2 arguments as part of the Module API now.

File: src/index.js (hunk 1 above)
Comment (Kovensky) [reply src/index.js]: That's actually not up to css-loader, but up to the ETWP loader's pitching result. The pitch result is a commonjs module, so even if css-loader is converted, it won't be able to be picked by concatenated modules because it'll be required via commonjs.

**Comment by Kovensky** [comment]
@probablyup that problem wasn't with one file but with _all_ files; since ETWP is supposed to run on node instead of in a browser the default testEnvironment was wrong to begin with.

**Comment by michael-ciniawsky** [comment]
Released in [v4.0.0-beta.0](https://github.com/webpack-contrib/extract-text-webpack-plugin/releases/tag/v4.0.0-beta.0) 🎉 

ℹ️  Last release under `@next` if nothing urgent pops up :)
